/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dvdrent;

import java.util.LinkedList;
import java.util.List;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import org.bson.types.ObjectId;
import org.xml.sax.ext.LexicalHandler;

import models.ClientModel;
import models.DvdModel;

/**
 *
 * @author krutulj
 */
public class App extends javax.swing.JFrame {
	DBHelperImpl db = new DBHelperImpl();

	/**
	 * Creates new form App
	 */
	public App() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel10 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		nameTextField = new javax.swing.JTextField();
		surnameTextField = new javax.swing.JTextField();
		phoneTextField = new javax.swing.JTextField();
		addUserButton = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		titleTextField = new javax.swing.JTextField();
		genreTextField = new javax.swing.JTextField();
		yearTextField = new javax.swing.JTextField();
		lenghtTextField = new javax.swing.JTextField();
		addNewDvDButton = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		outputTextArea = new javax.swing.JTextArea();
		jPanel4 = new javax.swing.JPanel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		rentDvdButton = new javax.swing.JButton();
		clientIdTextField = new javax.swing.JTextField();
		dvdIdTextField = new javax.swing.JTextField();
		jPanel5 = new javax.swing.JPanel();
		jLabel11 = new javax.swing.JLabel();
		returnDvdId = new javax.swing.JTextField();
		returnDvdButton = new javax.swing.JButton();
		jPanel6 = new javax.swing.JPanel();
		listClientsButton = new javax.swing.JButton();
		listDvdsButton = new javax.swing.JButton();
		listClientsWhoRentButton = new javax.swing.JButton();
		listRentedDvdsButton = new javax.swing.JButton();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		optClientIdTextField = new javax.swing.JTextField();
		optDvdIdTextField = new javax.swing.JTextField();
		findClientButton = new javax.swing.JButton();
		findDvdButton = new javax.swing.JButton();
		removeClientButton = new javax.swing.JButton();
		removeDvdButton = new javax.swing.JButton();

		jLabel10.setText("jLabel10");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		jPanel1.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Client"));

		jLabel5.setText("Name:");

		jLabel6.setText("Surname:");

		jLabel7.setText("Phone:");

		addUserButton.setText("Add new user");
		addUserButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addUserButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING)
																														.addComponent(
																																jLabel5,
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel7,
																																javax.swing.GroupLayout.Alignment.LEADING))
																										.addGap(22,
																												22,
																												22))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel6)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								surnameTextField)
																						.addComponent(
																								nameTextField)
																						.addComponent(
																								phoneTextField)))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(0,
																				113,
																				Short.MAX_VALUE)
																		.addComponent(
																				addUserButton)))
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(
																nameTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(
																surnameTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																phoneTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel7))
										.addGap(38, 38, 38)
										.addComponent(addUserButton)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("DVD's"));

		jLabel1.setText("Title:");

		jLabel2.setText("Genre:");

		jLabel3.setText("Year:");

		jLabel4.setText("Lenght:");

		addNewDvDButton.setText("Add new DVD");
		addNewDvDButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addNewDvDButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel1)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jLabel3)
																						.addComponent(
																								jLabel4))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								titleTextField)
																						.addComponent(
																								genreTextField)
																						.addComponent(
																								lenghtTextField)
																						.addComponent(
																								yearTextField)))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(0,
																				66,
																				Short.MAX_VALUE)
																		.addComponent(
																				addNewDvDButton)))
										.addContainerGap()));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																titleTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel1))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																genreTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																yearTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																lenghtTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(addNewDvDButton)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jPanel3.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Output"));

		outputTextArea.setColumns(20);
		outputTextArea.setRows(5);
		jScrollPane1.setViewportView(outputTextArea);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel3Layout
						.createSequentialGroup()
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 322,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));

		jPanel4.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Rent DVD"));

		jLabel8.setText("Client id:");

		jLabel9.setText("DVD id:");

		rentDvdButton.setText("Rent DVD");
		rentDvdButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rentDvdButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel4Layout
																										.createSequentialGroup()
																										.addContainerGap()
																										.addGroup(
																												jPanel4Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addGroup(
																																jPanel4Layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jLabel8)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				clientIdTextField,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				73,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))
																														.addComponent(
																																jLabel9)))
																						.addGroup(
																								jPanel4Layout
																										.createSequentialGroup()
																										.addGap(67,
																												67,
																												67)
																										.addComponent(
																												dvdIdTextField,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												74,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addGap(0,
																				0,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel4Layout
																		.createSequentialGroup()
																		.addGap(0,
																				0,
																				Short.MAX_VALUE)
																		.addComponent(
																				rentDvdButton)))
										.addContainerGap()));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel8)
														.addComponent(
																clientIdTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel9)
														.addComponent(
																dvdIdTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(48, 48, 48)
										.addComponent(rentDvdButton)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jPanel5.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Return DVD"));

		jLabel11.setText("DVD id:");

		returnDvdButton.setText("Return");
		returnDvdButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				returnDvdButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout
				.setHorizontalGroup(jPanel5Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel5Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel11)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(returnDvdId))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel5Layout.createSequentialGroup()
										.addContainerGap(26, Short.MAX_VALUE)
										.addComponent(returnDvdButton)
										.addContainerGap()));
		jPanel5Layout
				.setVerticalGroup(jPanel5Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel5Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel11)
														.addComponent(
																returnDvdId,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(returnDvdButton)
										.addContainerGap()));

		jPanel6.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Options"));

		listClientsButton.setText("List all clients");
		listClientsButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						listClientsButtonActionPerformed(evt);
					}
				});

		listDvdsButton.setText("List all DVDs");
		listDvdsButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				listDvdsButtonActionPerformed(evt);
			}
		});

		listClientsWhoRentButton.setText("Clients who rent");
		listClientsWhoRentButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						listClientsWhoRentButtonActionPerformed(evt);
					}
				});

		listRentedDvdsButton.setText("Rented DVDs");
		listRentedDvdsButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						listRentedDvdsButtonActionPerformed(evt);
					}
				});

		jLabel12.setText("Client id:");

		jLabel13.setText("DVD id:");

		findClientButton.setText("find");
		findClientButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				findClientButtonActionPerformed(evt);
			}
		});

		findDvdButton.setText("find");
		findDvdButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				findDvdButtonActionPerformed(evt);
			}
		});

		removeClientButton.setText("remove");
		removeClientButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						removeClientButtonActionPerformed(evt);
					}
				});

		removeDvdButton.setText("remove");
		removeDvdButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				removeDvdButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
				jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout
				.setHorizontalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel6Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel6Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								listRentedDvdsButton,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								listClientsWhoRentButton,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE))
																		.addContainerGap())
														.addGroup(
																jPanel6Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel6Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel6Layout
																										.createSequentialGroup()
																										.addComponent(
																												listClientsButton)
																										.addGap(18,
																												18,
																												18)
																										.addComponent(
																												listDvdsButton,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												109,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(0,
																												0,
																												Short.MAX_VALUE))
																						.addGroup(
																								jPanel6Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel6Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																false)
																														.addGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																jPanel6Layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jLabel12)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				optClientIdTextField))
																														.addGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																jPanel6Layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jLabel13)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																		.addComponent(
																																				optDvdIdTextField,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												jPanel6Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																false)
																														.addComponent(
																																findClientButton,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE)
																														.addComponent(
																																findDvdButton,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												jPanel6Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																removeClientButton,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE)
																														.addGroup(
																																jPanel6Layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				removeDvdButton)
																																		.addGap(0,
																																				0,
																																				Short.MAX_VALUE)))))
																		.addGap(12,
																				12,
																				12)))));
		jPanel6Layout
				.setVerticalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																listClientsButton)
														.addComponent(
																listDvdsButton))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(listClientsWhoRentButton)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(listRentedDvdsButton)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel12)
														.addComponent(
																optClientIdTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																findClientButton)
														.addComponent(
																removeClientButton))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel13)
														.addComponent(
																optDvdIdTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																findDvdButton)
														.addComponent(
																removeDvdButton))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(2, 2, 2)
								.addComponent(jPanel4,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jPanel5,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel6,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												false)
												.addComponent(
														jPanel5,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jPanel4,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jPanel2,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														0, Short.MAX_VALUE)
												.addComponent(
														jPanel1,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jPanel6,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														0, Short.MAX_VALUE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel3,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private static void log(String text) {
		outputTextArea.append(text + "\n");
	}

	private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addUserButtonActionPerformed
		String name, surname, phone;
		name = nameTextField.getText();
		surname = surnameTextField.getText();
		phone = phoneTextField.getText();
		ClientModel clientToSave = new ClientModel(name, surname, phone);
		ObjectId clientId = db.addClient(clientToSave);
		if (clientId != null) {
			ClientModel cm = db.findClient(clientId);
			log(cm + " has been created");
		} else {
			log("ERROR!!! client " + clientToSave
					+ " hasn't been saved to database");
		}
	}// GEN-LAST:event_addUserButtonActionPerformed

	private void addNewDvDButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addNewDvDButtonActionPerformed
		String title, genre, year, lenght;
		title = titleTextField.getText();
		genre = genreTextField.getText();
		year = yearTextField.getText();
		lenght = lenghtTextField.getText();
		DvdModel dvdToSave = new DvdModel(null, title, genre, Integer.parseInt(year),
				Integer.parseInt(lenght));
		ObjectId dvdId = db.addDVD(dvdToSave);
		if (dvdId != null) {
			DvdModel dm = db.findDvd(dvdId);
			log(dm + " has been created");
		} else {
			log("ERROR!!! dvd " + dvdToSave + " hasn't been saved to database");
		}

	}// GEN-LAST:event_addNewDvDButtonActionPerformed

	private void rentDvdButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rentDvdButtonActionPerformed
		ObjectId clientId, dvdId;
		clientId = new ObjectId(clientIdTextField.getText().toString());
		dvdId = new ObjectId(dvdIdTextField.getText().toString());
		
		ClientModel client = db.findClient(clientId);
		
		DvdModel dvd = db.findDvd(dvdId);
		if (client == null) {
			log("ERROR!!! client with Id:" + clientId
					+ " not found in database!");
			return;
		}
		if (dvd == null) {
			log("ERROR!!! dvd with Id:" + dvdId + " not found in database!");
			return;
		}

		db.rentDvd(clientId, dvdId);
		log("DVD " + dvd.getTitle() + " has been rented for "
				+ client.getName() + " " + client.getSurname());
	}// GEN-LAST:event_rentDvdButtonActionPerformed

	private void returnDvdButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_returnDvdButtonActionPerformed
		ObjectId dvdId = new ObjectId(returnDvdId.getText());
		DvdModel dvd = db.findDvd(dvdId);
		if (dvd == null) {
			log("ERROR!!! dvd with Id:" + dvdId + " not found in database!");
			return;
		}

		dvd.setRentedBy(null);
		ObjectId updatedDvdId = db.updateDVD(dvd);
		if (updatedDvdId != null && updatedDvdId == dvdId) {
			log("dvd " + dvdId + " has been updated");
		} else {
			log("ERROR!!! dvd with Id:" + dvdId + " hasn't been updated!");
		}

	}// GEN-LAST:event_returnDvdButtonActionPerformed

	private void listClientsButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_listClientsButtonActionPerformed
		List<ClientModel> list = (List<ClientModel>) db.listClients();
		for (ClientModel cm : list) {
			log(cm.toString());
		}
	}// GEN-LAST:event_listClientsButtonActionPerformed

	private void listDvdsButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_listDvdsButtonActionPerformed
		List<DvdModel> list = (List<DvdModel>) db.listDvds();
		for (DvdModel dm : list) {
			log(dm.toString());
		}
	}// GEN-LAST:event_listDvdsButtonActionPerformed

	private void listClientsWhoRentButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_listClientsWhoRentButtonActionPerformed
		List<ClientModel> clientsWhoRent = new LinkedList<>();
		List<DvdModel> rentedDvds = listOfRentedDvds();

		for (DvdModel rented : rentedDvds) {
			ClientModel rentedBy = db.findClient(rented.getRentedBy());
			if (!clientsWhoRent.contains(rentedBy)) {
				clientsWhoRent.add(rentedBy);
			}
		}

		log("List of clients who rent at least one dvd");
		for (ClientModel cwr : clientsWhoRent) {
			log(cwr.toString());
		}

	}// GEN-LAST:event_listClientsWhoRentButtonActionPerformed

	private void listRentedDvdsButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_listRentedDvdsButtonActionPerformed
		List<DvdModel> list = (List<DvdModel>) db.listDvds();
		log("List of rented dvd's");
		for (DvdModel dm : list) {
			if (dm.getRentedBy() != null) {
				log(dm + " rented by " + dm.getRentedBy());
			}
		}
	}// GEN-LAST:event_listRentedDvdsButtonActionPerformed

	private void findClientButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_findClientButtonActionPerformed
		ObjectId clientId = new ObjectId(optClientIdTextField.getText());
		ClientModel client = db.findClient(clientId);
		List<DvdModel> listOfRentedDvds;
		if (client == null) {
			log("Client with Id:" + clientId + " not found in database!");
			return;
		}

		listOfRentedDvds = listOfRentedDvdsByClient(client);

		log("Information about Client [" + clientId + "]");
		log("Name: " + client.getName());
		log("Surname: " + client.getSurname());
		log("Phone: " + client.getPhone());
		if (listOfRentedDvds.size() > 0) {
			log("List Of rented DVDs: ");
			for (DvdModel dm : listOfRentedDvds) {
				log(dm.toString());
			}
		} else {
			log("Client does not have borrowed dvd");
		}

	}// GEN-LAST:event_findClientButtonActionPerformed

	private void removeClientButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_removeClientButtonActionPerformed
		ObjectId clientId = new ObjectId(optClientIdTextField.getText());
		ClientModel client = db.findClient(clientId);
		if (client == null) {
			log("Client with Id:" + clientId + " not found in database!");
			return;
		}

		boolean success = db.removeClient(client.getId());
		if (success) {
			log("Client " + client + " has been removed from database");
		} else {
			log("ERROR!!! " + client + " hasn't been removed from database");
		}
	}// GEN-LAST:event_removeClientButtonActionPerformed

	private void findDvdButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_findDvdButtonActionPerformed
		ObjectId dvdId = new ObjectId(optDvdIdTextField.getText());
		DvdModel dvd = db.findDvd(dvdId);
		if (dvd == null) {
			log("dvd with Id:" + dvdId + " not found in database!");
			return;
		}
		log("Information about Dvd [" + dvdId + "]");
		log("Title: " + dvd.getTitle());
		log("Genre: " + dvd.getGenre());
		log("Year: " + dvd.getYear());
		log("Lenght: " + dvd.getLenght());
		ClientModel rentedBy = db.findClient(dvd.getRentedBy());

		if (rentedBy != null) {
			log("Rented By: " + rentedBy);
		} else {
			log("dvd is avaliable");
		}

	}// GEN-LAST:event_findDvdButtonActionPerformed

	private void removeDvdButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_removeDvdButtonActionPerformed
		ObjectId dvdId = new ObjectId(optDvdIdTextField.getText());
		DvdModel dvd = db.findDvd(dvdId);
		if (dvd == null) {
			log("dvd with Id:" + dvdId + " not found in database!");
			return;
		}

		boolean success = db.removeClient(dvd.getId());
		if (success) {
			log("dvd " + dvd + " has been removed from database");
		} else {
			log("ERROR!!! " + dvd + " hasn't been removed from database");
		}
	}// GEN-LAST:event_removeDvdButtonActionPerformed

	private List<DvdModel> listOfRentedDvdsByClient(ClientModel cm) {
		LinkedList<DvdModel> listOfDvds = new LinkedList<>();
		LinkedList<DvdModel> allRentedDvds = (LinkedList<DvdModel>) listOfRentedDvds();

		for (DvdModel rd : allRentedDvds) {
			if (rd.getRentedBy() == cm.getId()) {
				listOfDvds.add(rd);
			}
		}
		return listOfDvds;
	}

	private List<DvdModel> listOfRentedDvds() {
		List<DvdModel> list = (List<DvdModel>) db.listDvds();
		List<DvdModel> rented = new LinkedList<>();
	
		for (DvdModel dm : list) {
			if (dm.getRentedBy() != null) {
				rented.add(dm);
			}
		}
		return rented;
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		 try {
	            // Set System L&F
	        UIManager.setLookAndFeel(
	            UIManager.getSystemLookAndFeelClassName());
	    } 
	    catch (UnsupportedLookAndFeelException e) {
	       // handle exception
	    }
	    catch (ClassNotFoundException e) {
	       // handle exception
	    }
	    catch (InstantiationException e) {
	       // handle exception
	    }
	    catch (IllegalAccessException e) {
	       // handle exception
	    }
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new App().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton addNewDvDButton;
	private javax.swing.JButton addUserButton;
	private javax.swing.JTextField clientIdTextField;
	private javax.swing.JTextField dvdIdTextField;
	private javax.swing.JButton findClientButton;
	private javax.swing.JButton findDvdButton;
	private javax.swing.JTextField genreTextField;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField lenghtTextField;
	private javax.swing.JButton listClientsButton;
	private javax.swing.JButton listClientsWhoRentButton;
	private javax.swing.JButton listDvdsButton;
	private javax.swing.JButton listRentedDvdsButton;
	private javax.swing.JTextField nameTextField;
	private javax.swing.JTextField optClientIdTextField;
	private javax.swing.JTextField optDvdIdTextField;
	private static javax.swing.JTextArea outputTextArea;
	private javax.swing.JTextField phoneTextField;
	private javax.swing.JButton removeClientButton;
	private javax.swing.JButton removeDvdButton;
	private javax.swing.JButton rentDvdButton;
	private javax.swing.JButton returnDvdButton;
	private javax.swing.JTextField returnDvdId;
	private javax.swing.JTextField surnameTextField;
	private javax.swing.JTextField titleTextField;
	private javax.swing.JTextField yearTextField;
	// End of variables declaration//GEN-END:variables
}
